import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import i18nConfig from '@/app/i18n/i18n.config'
import { dir } from 'i18next'
import Navigation from '../components/Navigation'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export function generateStaticParams() {
    return i18nConfig.locales.map((locale) => ({ locale }))
}

export default function RootLayout({ children, params: { locale } }: any) {
    return (
        <html lang={locale} dir={dir(locale)}>
            <body className={inter.className}>
                <div className="mx-auto max-w-10xl ">
                    <Navigation />
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    )
}
