import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import i18nConfig from '@/app/i18n/i18n.config'
import { dir } from 'i18next'
import Navigation from '../components/Navigation'
import Footer from '../components/Footer'
import initTranslations from '@/app/i18n/i18n'
import TranslationsProvider from '../components/TranslationProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const i18nNamespaces = ['common']

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params: { locale },
}: any) {
  const { t, resources } = await initTranslations(locale, ['common'])

  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={inter.className}>
        <div className="mx-auto max-w-10xl ">
          <TranslationsProvider
            namespaces={i18nNamespaces}
            locale={locale}
            resources={resources}
          >
            <Navigation />
            <div className="min-h-dvh my-4 px-4 md:px8 max-w-8xl mx-auto">
              {children}
            </div>
            <Footer />
          </TranslationsProvider>
        </div>
      </body>
    </html>
  )
}
